### ISSUE TITLE
got panic when call AllDBs with options

### ISSUE THREAD

**Issue by sunbird1015** [go-kivik/kivik#1048]
## Bug Report Checklist (remove this template if submitting a feature request)

got panic when call AllDBs with options:
panic({0x10db16f80?, 0x1590977d0?})
	runtime/panic.go:785 +0x134
net/url.Values.Add(...)
	net/url/url.go:939
github.com/go-kivik/kivik/v4.params.Apply(0xc000090320?, {0x10db33580?, 0xc00031e098})
	github.com/go-kivik/kivik/v4@v4.3.2/options.go:95 +0x545
github.com/go-kivik/kivik/v4.multiOptions.Apply(...)
	github.com/go-kivik/kivik/v4@v4.3.2/options.go:46
github.com/go-kivik/kivik/v4/couchdb.(*client).AllDBs(0xc00012b110, {0x10db5f770, 0xc00038a100}, {0x1590992f8, 0xc00021c1b0})
	github.com/go-kivik/kivik/v4@v4.3.2/couchdb/client.go:33 +0x7c
github.com/go-kivik/kivik/v4.(*Client).AllDBs(0xc000119040, {0x10db5f770, 0xc00038a100}, {0xc0002e88b0, 0x1, 0x1})
	github.com/go-kivik/kivik/v4@v4.3.2/kivik.go:145 +0xff

maybe change [var query url.Values] to [query := url.Values{}] of func AllDBs in https://github.com/go-kivik/kivik/blob/master/couchdb/client.go

**Comment by flimzy** [comment]
Can you add an example of the code you're using that panics?

**Comment by sunbird1015** [comment]
use param in AllDBs func call will cause panic:
client.AllDBs(ctx, kivik.Param("startkey", startkey))

**Comment by flimzy** [comment]
I really need a complete, reproducible test case. The bug report template exists for a reason, but you deleted it when filing this bug, rather than giving me the important information I need to solve the bug.
