### ISSUE TITLE
Kivik now used by the Cayley open source graph database

### ISSUE THREAD

**Issue by elliott5** [go-kivik/kivik#309]
https://github.com/cayleygraph/cayley/releases/tag/v0.7.1

Well done for providing such a reliable platform.

You may wish to mention the `cayleygraph` project as a user of `kivik`.

**Comment by flimzy** [comment]
Thanks for the report! It might also be worth passing this along to the [CouchDB Weekly Newsletter](https://blog.couchdb.org/2018/01/25/) (submission link at the bottom of the page).

**Comment by elliott5** [comment]
I've written two tweets mentioning `@CouchDB` and I will e-mail the newsletter a link to this issue.

https://twitter.com/ElliottStoneham/status/958621137293991937

https://twitter.com/ElliottStoneham/status/958618672817373188

**Comment by elliott5** [comment]
E-mail to CouchDB newsletter:

> The Cayley open-source graph database now has a CouchDB/PouchDB back-end. The PouchDB back-end works in the browser.
>
> Find out more about Cayley at https://cayley.io/ or see the detailed announcement at https://github.com/cayleygraph/cayley/releases/tag/v0.7.1.
>
> The backend was made possible by the http://kivik.io/ CouchDB and PouchDB library for Go.
