### ISSUE TITLE
Installation failed (https://github.com/go-kivik/kivik/tree/stable1.x#installation)!

### ISSUE THREAD

**Issue by SerkanSipahi** [go-kivik/kivik#311]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?

>https://github.com/go-kivik/kivik/tree/stable1.x

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.

>go1.9.2

3. What did you do? (Include your code if possible)

>https://github.com/go-kivik/kivik/tree/stable1.x#installation
go get -u github.com/flimzy/kivik

4. What did you expect to see?

>no installation errors

5. What did you see instead?

>package github.com/flimzy/kivik: code in directory /Users/ssipahi/go/src/github.com/flimzy/kivik expects import "github.com/go-kivik/kivik"

Whats going wrong?

**Comment by flimzy** [comment]
`go get github.com/flimzy/kivik` will install the latest (development) version of Kivik. To use the stable version, you'll need to use a dependency tool, such as `go dep`, as [documented in the README](https://github.com/go-kivik/kivik#versions).

**Comment by SerkanSipahi** [comment]
thank you
