### ISSUE TITLE
How to ensure read consistency when using /_find?

### ISSUE THREAD

**Issue by stefanberger** [go-kivik/kivik#315]
The `/<db>/_find` method does not seem to ensure read consistency in a cluster setup since it is assuming the read quorum to always be '1': http://docs.couchdb.org/en/2.1.1/api/database/find.html#post--db-_find

To solve this I am trying to find an API to determine the necessary read quorum. The necessary information is returned starting with CouchDB 2.1.1 in `/<db>`: http://docs.couchdb.org/en/2.1.1/api/database/common.html. The idea would be to read the cluster info's `r` parameter and copy that into the options of the Find() method. What API should I use to get `/<db>`?

**Comment by stefanberger** [comment]
The following patch would allow a client to get the database info. Commments?
```
diff --git a/vendor/github.com/flimzy/kivik/driver/driver.go b/vendor/github.com/flimzy/kivik/driver/driver.go
index 39aa5f35..2ac2af50 100644
--- a/vendor/github.com/flimzy/kivik/driver/driver.go
+++ b/vendor/github.com/flimzy/kivik/driver/driver.go
@@ -27,6 +27,22 @@ type Version struct {
 	RawResponse json.RawMessage
 }
 
+type DBInfo struct {
+	Cluster map[string]int `json:"cluster,omitempty"`
+	CompactRunning bool `json:"CompactRunning,omitempty"`
+	DBName string `json:"db_name,omitempty"`
+	DiskFormatVersion int `json:"disk_format_version,omitempty"`
+	DataSize int `json:"data_size"`
+	DiskSize int `json:"disk_size"`
+	DocCount int `json:"doc_count"`
+	DocDelCount int `json:"doc_del_count"`
+	InstanceStartTime string `json:"instance_start_time"`
+	Other interface{} `json:Other`
+	PurgeSeq int `json:PurgeSeq`
+	Sizes map[string]int `json:sizes`
+	UpdateSeq int `json:update_seq`
+}
+
 // Client is a connection to a database server.
 type Client interface {
 	// Version returns the server implementation's details.
@@ -43,6 +59,7 @@ type Client interface {
 	DestroyDB(ctx context.Context, dbName string, options map[string]interface{}) error
 	// DB returns a handleto the requested database
 	DB(ctx context.Context, dbName string, options map[string]interface{}) (DB, error)
+	DBInfo(ctx context.Context, dbName string) (*DBInfo, error)
 }
 
 // Replication represents a _replicator document.
diff --git a/vendor/github.com/flimzy/kivik/kivik.go b/vendor/github.com/flimzy/kivik/kivik.go
index deb0625a..65cb004d 100644
--- a/vendor/github.com/flimzy/kivik/kivik.go
+++ b/vendor/github.com/flimzy/kivik/kivik.go
@@ -121,6 +121,34 @@ func (c *Client) DBExists(ctx context.Context, dbName string, options ...Options
 	return c.driverClient.DBExists(ctx, dbName, opts)
 }
 
+type DBInfo struct {
+	Cluster map[string]int `json:"cluster,omitempty"`
+	CompactRunning bool `json:"CompactRunning,omitempty"`
+	DBName string `json:"db_name,omitempty"`
+	DiskFormatVersion int `json:"disk_format_version,omitempty"`
+	DataSize int `json:"data_size"`
+	DiskSize int `json:"disk_size"`
+	DocCount int `json:"doc_count"`
+	DocDelCount int `json:"doc_del_count"`
+	InstanceStartTime string `json:"instance_start_time"`
+	Other interface{} `json:Other`
+	PurgeSeq int `json:PurgeSeq`
+	Sizes map[string]int `json:sizes`
+	UpdateSeq int `json:update_seq`
+}
+
+// DBExists returns true if the specified database exists.
+func (c *Client) DBInfo(ctx context.Context, dbName string) (*DBInfo, error) {
+	dbi, err := c.driverClient.DBInfo(ctx, dbName)
+	if err != nil {
+		return nil, err
+	}
+	return &DBInfo {
+		Cluster: dbi.Cluster,
+		CompactRunning: dbi.CompactRunning,
+	}, nil
+}
+
 // CreateDB creates a DB of the requested name.
 func (c *Client) CreateDB(ctx context.Context, dbName string, options ...Options) error {
 	opts, err := mergeOptions(options...)
diff --git a/vendor/github.com/go-kivik/couchdb/client.go b/vendor/github.com/go-kivik/couchdb/client.go
index 1013c99d..0a431622 100644
--- a/vendor/github.com/go-kivik/couchdb/client.go
+++ b/vendor/github.com/go-kivik/couchdb/client.go
@@ -27,6 +27,15 @@ func (c *client) DBExists(ctx context.Context, dbName string, _ map[string]inter
 	return err == nil, err
 }
 
+func (c *client) DBInfo(ctx context.Context, dbName string) (*driver.DBInfo, error) {
+	if dbName == "" {
+		return nil, missingArg("dbName")
+	}
+	var result driver.DBInfo
+	_, err := c.DoJSON(ctx, kivik.MethodGet, dbName, nil, &result)
+	return &result, err
+}
+
 func (c *client) CreateDB(ctx context.Context, dbName string, _ map[string]interface{}) error {
 	if dbName == "" {
 		return missingArg("dbName")
```

**Comment by flimzy** [comment]
Help me understand the desired behavior:  Are you trying to just _read_ meta data about the database?  Or do you need to change the `/db/_find` behavior?

Re: your patch, it would be easier to review if it were a PR.  But just by looking at it, is that functionality not already provided by the [DB.Stats](https://godoc.org/github.com/go-kivik/kivik#DB.Stats) method?

**Comment by stefanberger** [comment]
I would like to change the `/{db}/_find` behavior and set the `r' parameter in the query to a value that provides read-consistency. http://docs.couchdb.org/en/latest/api/database/find.html

To get to that `r` value I need the cluster information from the `/{db}` URL. I don't think the DB.Stats method has that information. Here's what I get from a Cloudant:

```
# curl -XGET https://64b40286-4fad-4454-b691-b0f1b0907376-bluemix:${password}@64b40286-4fad-4454-b691-b0f1b0907376-bluemix.cloudant.com/test1
{
   "update_seq":"5-g1AAAAHveJzLYWBg4MhgTmFQSUlKzi9KdUhJstBLytVNTtZNK0rUNTDUS87JL01JzCvRy0styQGqZkpkSJL___9_ViIDSJ8qXJ-hAQGNSQpAMskerJeRNDuTHEBa4xFaSbE2AaS3HuFk4q3NYwGSDA1ACqh7Puk-huhfANG_n2RfQ7QfgGi_n5XIRJb1DyD6Qb7PAgB7S53b",
   "db_name":"test1",
   "sizes":{
      "file":154239,
      "external":20,
      "active":5211
   },
   "purge_seq":0,
   "other":{
      "data_size":20
   },
   "doc_del_count":0,
   "doc_count":5,
   "disk_size":154239,
   "disk_format_version":6,
   "data_size":5211,
   "compact_running":false,
   "cluster":{
      "q":8,
      "n":3,
      "w":2,
      "r":2
   },
   "instance_start_time":"0"
}
```

The 'r' and 'w' values seems to be each set to `round_down(n/2)+1 -> r > n/2; w > n/2; r + w > n`. So, these settings provide read and write consistency but not for the find operation. It also seems that if one re-configures CouchDB these values get adjusted to this formula so that read and write consistency is ensured.

The idea is to read the cluster values from the DB once, cache them, and use them in the find operation.

FYI: I need it for this PR: https://github.com/theupdateframework/notary/pull/1279

**Comment by flimzy** [comment]
Thanks for the clarification.

It sounds like simply expanding `DB.Stats` to include the `cluster` object would be sufficient, is that right?

**Comment by stefanberger** [comment]
Also that is a possibility.

**Comment by flimzy** [comment]
I think that change will be trivial, and easy to backport to kivik 1.x.  I'll try to make that change this evening after work. While I'm at it, I'll probably add a field to the `DBStats` struct to expose the raw JSON response, to be more future-proof should new data be added in the future as well.

I can then leave this issue open for a while longer, to discuss options for caching that value, if you feel that's still desirable.

**Comment by stefanberger** [comment]
Would it be possible for the Find() operation to take a parameter that ensures read-consistency?

**Comment by flimzy** [comment]
> Would it be possible for the Find() operation to take a parameter that ensures read-consistency?

It's already possible to pass the `r` value to the `Find()` method, as part of the `query` object, of course.

I suppose you're thinking of something that automatically queries (and caches) those values from the server, as your above patch does? Would you see this affecting other queries, too?  `Get()`, etc?

Maybe this type of thing belongs in a DB-scoped configuration?

**Comment by stefanberger** [comment]
The way I understand the description of `/{db}`, read consistency should be ensured for all 'normal' read and write operations: http://docs.couchdb.org/en/latest/api/database/common.html

```
cluster.r (number) – Read quorum. The number of consistent copies of a document that need to be read before a successful reply.
cluster.w (number) – Write quorum. The number of copies of a document that need to be written before a successful reply
```

I think the `find` operation is an exception. For normal reading and writing one could just say I am willing to risk in-consitent reads and writes by providing a lower `r` or `w` value respectively, such as `r=1` for `n=3`, otherwise consistency is ensured. At least that's how I interpret the documentation.

**Comment by flimzy** [comment]
Based on the [`_find` docs](http://docs.couchdb.org/en/2.1.1/api/database/find.html#post--db-_find):

> **r** (number) – Read quorum needed for the result. This defaults to 1, in which case the document found in the index is returned. 

it sounds like the exception may be due simply to how the find indexes are built, in a way similar to the standard/legacy views, with the exception that the _find index always indexes the full document (rather than a custom value emitted by the map function).

Since the find index always indexes the full document, returning that is an easy performance shortcut, which is not available to standard views (if my guessing and reading between the lines is accurate).  Putting this another way, the closest analog is the legacy view functions, and adding support for `r` to a standard view would be non-trivial and non-idiomatic, as it would require re-running the map() function on N shards before returning a result--to say nothing of the complexity added by achieving a quorum for aggregate queries of views.

Although none of this really gets me much closer to a clear solution :)

**Comment by stefanberger** [comment]
From the driver user perspective being able to figure out the appropriate `r` parameter value seems helpful. Whether one passes that in to the find operation with that number is a different issue. 

My guess is that with `r > 1` a read of the referenced document is done and if the one in the index has now already been replaced with an update on one machine, then nothing is returned for that document. I am not quite sure how to best deal with that on the client side, but passing in an 'r' parameter seems like the right thing to do ?!

**Comment by flimzy** [comment]
The ability to read the `cluster` config is now in v1.8.0 of go-kivik/kivik and go-kivik/couchdb.

**Comment by flimzy** [comment]
I think this is sufficiently solved, so will close the issue. If any further work is necessary, please feel free to comment, and this can be re-opened.
