### ISSUE TITLE
kivik: doc is nil; does the query include docs?

### ISSUE THREAD

**Issue by s-frostick** [go-kivik/kivik#362]
I'm trying to get all the documents from a database. Maybe I'm missing something

1. Which version of Kivik are you using?
https://github.com/go-kivik/kivik/

2. Which version of Go are you using? 
go version go1.12 linux/amd64

3. What did you do? 
```
type couchdbRegistration struct {
	ID                  string              `json:"_id"`
	Rev                 string              `json:"_rev,omitempty"`
	RegistrationRequest RegistrationRequest `json:"RegistrationRequest"`

db := c.client.DB(context.TODO(), "registration")
rows, err := db.AllDocs(context.TODO())

for rows.Next() {
 var registration couchdbRegistration
 if err := rows.ScanDoc(&registration); err != nil {
     panic(err)
 }
fmt.Println(registration.RegistrationRequest)
}
```
4. What did you expect to see?
Print RegistrationRequests from documents retrieved from database 

5. What did you see instead?
Panic:
kivik: doc is nil; does the query include docs?

**Comment by flimzy** [comment]
By default, `_all_docs` (or any view) just returns the keys from the view. To include documents, you must pass the appropriate [option](https://docs.couchdb.org/en/stable/api/ddoc/views.html#api-ddoc-view):

    rows, err := db.AllDocs(context.TODO(), kivik.Options{"include_docs": true})

**Comment by s-frostick** [comment]
Great, that has solved my issue.

Thanks!

**Comment by Vinggui** [comment]
> By default, `_all_docs` (or any view) just returns the keys from the view. To include documents, you must pass the appropriate [option](https://docs.couchdb.org/en/stable/api/ddoc/views.html#api-ddoc-view):
> 
> ```
> rows, err := db.AllDocs(context.TODO(), kivik.Options{"include_docs": true})
> ```

I understand that it may be a decision based on the CouchDB API, but this command does not look obvious for me.

**Comment by flimzy** [comment]
Yes, this is because of the CouchDB API. See [here](http://docs.couchdb.org/en/stable/api/ddoc/views.html#api-ddoc-view). It is quite common (perhaps even the most common case) to query a view without retrieving the documents.

**Comment by Vinggui** [comment]
I think is just the name of the function itself (AllDocs). It resembles retrieving all docs and nothing related to a "view". I am sorry if this confusion is caused by lower knowledge of CouchDB's procedures, but the function name isn't quite clear about using a view for that, nor I found the documentation explicit about it.
Thanks for explaining it though!

**Comment by flimzy** [comment]
I see your point.

Although even for all docs, it's not uncommon to just want a list of documents, and not the entire contents.
