### ISSUE TITLE
Query with keys in v.1.8.1

### ISSUE THREAD

**Issue by mibes** [go-kivik/kivik#365]
1. Which version of Kivik are you using?
stable v.1.8.1

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
go1.12.1 darwin/amd64

3. What did you do? (Include your code if possible)
Run a query against a view with many keys

4. What did you expect to see?
A POST with the keys array in the body

5. What did you see instead?
A GET request

In the development branch the Query is evaluated to check if (multiple) keys are being requested:

``` Go
func (d *db) rowsQuery(ctx context.Context, path string, opts map[string]interface{}) (driver.Rows, error) {
	query, err := optionsToParams(opts)
	if err != nil {
		return nil, err
	}
	options := &chttp.Options{Query: query}
	method := kivik.MethodGet
	if keys, ok := query["keys"]; ok {
		method = kivik.MethodPost
		options.Body = chttp.EncodeBody(map[string][]string{
			"keys": keys,
		})
		delete(query, "keys")
	}
	resp, err := d.Client.DoReq(ctx, method, d.path(path), options)
	if err != nil {
		return nil, err
	}
	if err = chttp.ResponseError(resp); err != nil {
		return nil, err
	}
	return newRows(resp.Body), nil
}
```

In the stable release this is not the case:

``` Go
func (d *db) rowsQuery(ctx context.Context, path string, opts map[string]interface{}) (driver.Rows, error) {
	options, err := optionsToParams(opts)
	if err != nil {
		return nil, err
	}
	resp, err := d.Client.DoReq(ctx, kivik.MethodGet, d.path(path, options), nil)
	if err != nil {
		return nil, err
	}
	if err = chttp.ResponseError(resp); err != nil {
		return nil, err
	}
	return newRows(resp.Body), nil
}
```

Is there a chance to have this feature be back ported into 1.8.1 / 1.8.2? 

We're looking at optimising performance of our solution by means of views and this is a feature we're lacking at the moment.

Thanks!
Marcel

**Comment by flimzy** [comment]
This seems like a reasonable change, as it doesn't alter the API at all, and arguably, it can be considered a bug fix. However, it's not entirely straight forward to back-port this change to 1.8.x, because it depends on a number of other changes.

I'd welcome a PR to add this functionality to 1.8.x, or I may try to tackle it on my own as time permits.

**Comment by mibes** [comment]
Hi Jonathan, an alternative may be to tag the current development release with a version. Something like v1.9.x, or something else indicating that it is an unstable release. We're using Go modules and are having a hard time importing anything newer than v.1.8.1.

With the tag(s) we should be able to depend on the development release in a controlled manner. Happy to report on any issues we may find.

PS.
I will have a look at the PR, but like you found out that the change has some dependencies that weren't immediately obvious. Not sure how deep the rabbit hole is going to be. 😄

**Comment by flimzy** [comment]
I have now tagged a [2.0.0-pre1](https://github.com/go-kivik/kivik/releases/tag/v2.0.0-pre1) version, which should make it easier to follow the development branch with vendoring tools.
