### ISSUE TITLE
db.Query fails

### ISSUE THREAD

**Issue by stratg5** [go-kivik/kivik#366]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
v1.8.1

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
go1.11.8

3. What did you do? (Include your code if possible)
rows, err := db.AllDocs(context.TODO(), map[string]interface{}{
			"include_docs": true,
			"startkey":     "foo",
			"endkey":       "foo" + kivik.EndKeySuffix,
		})

4. What did you expect to see?
Values returned from couch where the id starts with foo.

5. What did you see instead?
Error stating that the values are not in utf8 format. I had to do the following instead -
rows, err := db.AllDocs(context.TODO(), map[string]interface{}{
			"include_docs": true,
			"startkey":     fmt.Sprintf("%q", id),
			"endkey":       fmt.Sprintf("%q", id+kivik.EndKeySuffix),
		})

It's subtle, wrapping the start and end keys in quotes, but very frustrating when I'm doing exactly what the documentation says to do and it fails. 

Maybe make the error clearer, or have the code wrap the keys in quotes for the user, or update the documentation. db.Query gives the same result, which is what the documentation says to do.

**Comment by flimzy** [comment]
Thanks for the report. I believe the necessary fix is just to update the documentation. The error message is generated by the server, so beyond Kivik's control. And automatically quoting the input would break the ability to use any compound keys.

#367 updates the godoc, and I have also updated the [wiki](https://github.com/go-kivik/kivik/wiki/Usage-Examples#query-a-view).

**Comment by stratg5** [comment]
Awesome, thanks @flimzy !!

**Comment by flimzy** [comment]
I agree it is a bit of a nuisance, to have to manually quote keys all the time. I could add a helper function to do it for you (i.e. `kivik.Key("foo")`), which would essentially json-marshal the string.

Another option might be to treat strings as raw strings to be quoted, and use a byte slice (or `json.RawMessage`) as raw JSON, for the use with compound keys.  If anyone has an opinion on this, I'd welcome feedback.

**Comment by stratg5** [comment]
Hm, not sure if this would work but what about the ability to pass in either key, or start key and end key, which handles complex keys. Each one may or may not append the kivik endkeysuffix for you, not sure if you want to take that away from the user.

**Comment by stratg5** [comment]
Sorry one more thing came to mind. When creating an index, I was getting errors there as well, it says to use an object like in the couch example but that was not working, I actually had to use something like this - map[string][]string{"fields": []string{"generic"}}. Not related, if you want me to open another issue i can?

**Comment by flimzy** [comment]
> Edit to clarify, if just key is passed in, we can assume thats the start and end key and escape that in quotes. If start and end are passed in, we quote both and query by those like normal. That handles both scenarios

No. Any of those fields, `key`, `startkey`, or `endkey`, may be any kind of JSON object, not just strings.

**Comment by flimzy** [comment]
> Not related, if you want me to open another issue i can?

Yes, please, a separate issue would be best.

**Comment by flimzy** [comment]
I have decided it makes sense to JSON-encode these keys (`endkey`, `startkey`, `key`, and `keys`), and will be making this change in https://github.com/go-kivik/couchdb/pull/176
