### ISSUE TITLE
Create index documentation seems off

### ISSUE THREAD

**Issue by stratg5** [go-kivik/kivik#368]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
v1.8.1

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
go version go1.11.8 darwin/amd64

3. What did you do? (Include your code if possible)
Created index using -

type field struct{
    Field string `json:"timestamp,omitempty"`
}

db.CreateIndex(context.TODO(), "json", "timestamp-json-index", []field{field{Field: "asc"})

4. What did you expect to see?
Expect to see the index created in couch

5. What did you see instead?
Index was not created, had to create it the following way instead:

db.CreateIndex(context.TODO(), "json", "timestamp-json-index", map[string][]string{"fields": []string{"timestamp"}})

This doesnt seem to follow the couch documentation so it was a bit confusing.

**Comment by flimzy** [comment]
Which documentation were you following that you found confusing?

**Comment by stratg5** [comment]
Sorry for the late reply, its under the create index documentation -

 index must be a valid index object, as described here: http://docs.couchdb.org/en/2.0.0/api/database/find.html#find-sort

but the object there is not valid for the create index method, it needs to be a map of string to list of strings instead of a list of maps or structs like in the couch db documentation. Slight difference but tricky to figure out going just off of errors returned by kivik.

**Comment by flimzy** [comment]
Thank you. That's simply the wrong link to the CouchDB docs. I'll update that.
