### ISSUE TITLE
How to update a document correctly?

### ISSUE THREAD

**Issue by gewubuntu** [go-kivik/kivik#369]
Hi i am running into a Update Conflict when updating my Document.

You mention :

cow.Rev = rev // Must be set

what do you mean by that? 

```
var sigObj candef.Signal
row := db.Get(context.TODO(), canID+"_"+signal.Name)
if err = row.ScanDoc(&sigObj); err != nil {
	panic(err)
}
dataValue := candef.GetDataValue(message.Data, sigObj.Offset, sigObj.Length)

newValue := candef.SlopeIntercept(sigObj.Value.Slope, sigObj.Value.Intercept, dataValue)
fmt.Printf("Signal Value = %v\n", newValue)

sigObj.Value.Value = newValue
newSigRev, err := db.Put(context.TODO(), sigObj.ID, sigObj)
if err != nil {
	panic(err)
}

sigObj.Rev = newSigRev
```

Am I doing this the right way or am I missing something?

**Comment by flimzy** [comment]
Whenever you update an existing document with PUT, you must include the current revision in that document. Otherwise, the server will reject the update with a 409 Conflict status.

Is that what you are seeing? Or are you experiencing some other error?

**Comment by flimzy** [comment]
I'm going to close this, as I have not received any updates. If this is still a problem, please feel free to comment, and I can re-open the issue.
