### ISSUE TITLE
go-kivik import order causes initialisation failure

### ISSUE THREAD

**Issue by ostenbom** [go-kivik/kivik#372]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
1.8.1

2. Which version of Go are you using?
go version go1.12.4 linux/amd64

3. What did you do? (Include your code if possible)
```
package main

import (
  "fmt"

  _ "github.com/go-kivik/couchdb" // The CouchDB driver
  "github.com/go-kivik/kivik"
)

func main() {
  client, err := kivik.New(context.Background(), "couch", host)
  if err != nil {
    panic(fmt.Sprintf("problems: %s", err))
  }
}

```

4. What did you expect to see?
Nothing

5. What did you see instead?
Problems: unknown driver "couch" (forgotten import?)

My linter forces alphabetic package ordering, putting `go-kivik/couchdb` at the top. If I use `flimzy/kivik`, the ordering changes (flimzy < go-kivik). And the problem disappears.

Initially I thought using `init()` in go-kivik might do the trick, since golang forces imported packages initialisation functions to run before its own `init()`.

Looking at `go-kivik/couchdb` I realise that it imports `flimzy/kivik` instead of `go-kivik/kivik` - perhaps this is why the initialisation isn't working the way it should.

What an odd quirk of having dev/stable in separate repositories!

**Comment by flimzy** [comment]
For the 1.x series of kivik, you must use `github.com/flimzy/kivik`. For the newer (unstable) version, which will become 2.x, use `github.com/go-kivik/kivik`.

**Comment by flimzy** [comment]
I've updated the documentation to hopefully be a bit more clear. Please let me know if further clarification or problems persist, and I'll do my best to address them.

**Comment by ToJen** [comment]
When should we switch to use `go-kivik/kivik`?

**Comment by flimzy** [comment]
`go-kivik/kivik` should be fully functional at the moment. But the API is likely (in fact, certain parts are certain) to change, before I tag it with a `2.0` version, so future upgrades could require you to change your client code in unexpected ways.

I hope to have the API stabilized within a month or two, but it largely depends on how much free time I have over the summer.

**Comment by ToJen** [comment]
Okay, no pressure, just asking because when I import `github.com/go-kivik/kivik`, GoLand says this: 

`'github.com/go-kivik/kivik' imports package that expects import "github.com/flimzy/kivik"`.

Then it says that I replace it with `flimzy/kivik`.

**Comment by flimzy** [comment]
That means you've somehow downloaded version 1.x, using the 2.x import path. How did you download kivik? With `go get`? Or are you using a vendoring tool? And if so, which one?

**Comment by ToJen** [comment]
Tried both `go get github.com/go-kivik/kivik` and `go get -u github.com/go-kivik/kivik`

**Comment by flimzy** [comment]
That should fetch the development version, which should not give you the error above. I suggest deleting kivik:

    rm -rf $GOPATH/src/github.com/go-kivik

Then re-installing it. Please let me know if that helps.

**Comment by ToJen** [comment]
It's still the same but is it ok to use `flimzy/kivik`?

**Comment by ToJen** [comment]
Here's some test code in a [gist](https://gist.github.com/ToJen/f6a4408ca47cb47cbf314e5eba96a82e).

**Comment by flimzy** [comment]
Yes, it's okay to use `flimzy/kivik`, and it's required if you want the stable branch.
