### ISSUE TITLE
BulkGet is missing from latest release version

### ISSUE THREAD

**Issue by stratg5** [go-kivik/kivik#382]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? 
1.8.1

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
go version go1.11.8 darwin/amd64

3. What did you do? (Include your code if possible)
Get latest version, try to do db.BulkGet()

4. What did you expect to see?
Expect to see this method available

5. What did you see instead?
It is not available

**Comment by flimzy** [comment]
Yes, this feature was added in the development branch only.  I have recently tagged version [2.0.0-pre1](https://github.com/go-kivik/kivik/releases/tag/v2.0.0-pre1), which you may begin using, if you really need this feature.
