### ISSUE TITLE
How do I mock *kivik.Row returned by kivik.Get()?

### ISSUE THREAD

**Issue by daniblum** [go-kivik/kivik#408]
I have this function that I would like to unit-test, and I haven't found yet a good solution for:
(from the Go Playground, minimalistic snapshot)

	package main
	import (
	"fmt"
		"context"
		"github.com/flimzy/kivik"
	)

	// KivikDBInterface interface
	type KivikDBInterface interface {
		Get(ctx context.Context, docID string, options ...kivik.Options) (*kivik.Row, error)
	}

	// couchStoreImpl implements the Store and CouchStore interfaces
	type couchStoreImpl struct {
		Store   KivikDBInterface
	}

	// Get returns the stored value of k
	func (cs *couchStoreImpl) Get(k string, v interface{}) error {
		row, err := cs.Store.Get(context.TODO(), string(k))
		if err != nil {
			return err
		}

		// unmarshal document in row to supplied interface
		if err = row.ScanDoc(&v); err != nil {
			return err
		}
		return nil
	}

	func main() {
		fmt.Println("Hello, playground")
	}

I use mockery to generate the mocks, this is the command I use:
	mockery -dir ... -name KivikDBInterface -inpkg -testonly

The problem I have is, Is there a somewhat elegant way of mocking the bold part, i. e. **row.ScanDoc()**?

My unit test uses the following:

	var mockDB MockKivikDBInterface
	mockDB.On("Get", mock.Anything, mock.AnythingOfType("string"), mock.AnythingOfType("kivik.Options")).Return(/*what to return here? */, nil)

I get this error if I try to instantiate a kivik.Row as follows:
row := kivik.Row{[]byte("hello")}
./prog.go:34:25: implicit assignment of unexported field 'doc' in kivik.Row literal

How should I approach this test instead?

Thank you,
Daniel

**Comment by flimzy** [comment]
Hi Daniel,

I've never used mockery, so can't really comment on how to use it. I have developed the [kivikmock](https://github.com/go-kivik/kivikmock) library, though, which can definitely mock that for you.

For example:

    func TestSomeFunc(t *testing.T) {
        client, mock := kivikmock.NewT(t)
        db := mock.NewDB()
        mock.ExpectDB().WithName("somedbname").WillReturn(db)
        db.ExpectGet().WithDocID("somedocid").WillReturn(kivikmock.DocumentT(`{"_id":"somedocid", ....}`)
       // Test your function here ...
        SomeFunc(client)
    }

Note that this only works with the latest version of Kivik. In your example above, you're using an old version, `github.com/flimzy/kivik`. You should use the latest import path, `github.com/go-kivik/kivik`.

I hope this is helpful.

**Comment by daniblum** [comment]
Thank you very much.
However, at the moment I cannot use the development version in my environment, I have to use the stable version.
When do you think this feature (the ability to use kivikmock) will be available in the stable version (i.e. github.com/flimzy/kivik, instead of github.com/go-kivik/kivik) ?

**Comment by flimzy** [comment]
I don't have any plans to port it to 1.x. 2.0 is already very stable, and will be officially tagged as such soon.
