### ISSUE TITLE
Changes feed deleted field is not reset to false after being set to true due to reusing the same struct

### ISSUE THREAD

**Issue by segevfiner** [go-kivik/kivik#420]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
fcc1de1f215b1a026cdb37f2e86a0bdee29c65f9

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
go version go1.12.9 darwin/amd64

3. What did you do? (Include your code if possible)
MWE for `go test`:
```go
package main

import (
	"context"
	"testing"

	_ "github.com/go-kivik/couchdb"
	"github.com/go-kivik/kivik"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const dbName = "changes_deleted_bug"

func TestChangesDeletedBug(t *testing.T) {
	client, err := kivik.New("couch", "http://localhost:5984/")
	require.NoError(t, err)

	err = client.CreateDB(context.TODO(), dbName)
	require.NoError(t, err)
	defer client.DestroyDB(context.TODO(), dbName)

	db := client.DB(context.TODO(), dbName)

	docID, rev, err := db.CreateDoc(context.TODO(), struct{}{})
	require.NoError(t, err)

	deleteRev, err := db.Delete(context.TODO(), docID, rev)
	require.NoError(t, err)

	docID2, rev2, err := db.CreateDoc(context.TODO(), struct{}{})
	require.NoError(t, err)

	changes, err := db.Changes(context.TODO())
	require.NoError(t, err)

	require.True(t, changes.Next())
	assert.Equal(t, docID, changes.ID())
	assert.Equal(t, deleteRev, changes.Changes()[0])
	assert.True(t, changes.Deleted())

	require.True(t, changes.Next())
	assert.Equal(t, docID2, changes.ID())
	assert.Equal(t, rev2, changes.Changes()[0])
	assert.False(t, changes.Deleted())

	assert.False(t, changes.Next())
	require.NoError(t, changes.Err())
}
```

`Gopkg.toml`:
```toml
[[constraint]]
  name = "github.com/go-kivik/kivik"
  branch = "master"

[[constraint]]
  name = "github.com/go-kivik/couchdb"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
```

4. What did you expect to see?
The test passes.

5. What did you see instead?
It fails:
```
=== RUN   TestChangesDeletedBug
--- FAIL: TestChangesDeletedBug (0.07s)
    main_test.go:45: 
                Error Trace:    main_test.go:45
                Error:          Should be false
                Test:           TestChangesDeletedBug
FAIL
exit status 1
FAIL    tests/kivik-changes-deleted-bug 0.083s
```

6. Analysis
I think this is caused by reusing the same `curVal` by the iterator on each iteration https://github.com/go-kivik/kivik/blob/fcc1de1f215b1a026cdb37f2e86a0bdee29c65f9/iterator.go#L82 without doing anything to reset it, and since the `deleted` field is what you would call in Go `omitempty` (It doesn't appear when it is `false`) it is not set by unmarshaling back to false once it has been set to `true`.

**Comment by flimzy** [comment]
Thanks for the bug report. Your fix is probably reasonable, but I want to write some unit tests first, to be sure it covers everything, and doesn't introduce any regressions, before I merge.

**Comment by segevfiner** [comment]
BTW, there might be a "cleaner" fix for this, for example instead of accepting `zeroValue` we can accept some factory to create a new `zeroValue` and call it each time, or maybe add some alternative way to reset it in place to save an allocation, or maybe there is something even better that I couldn't think of. But I didn't want to go into a large refactoring like this since I'm not really familiar with the entire code base.

**Comment by lionelvillard** [comment]
I ran into this issue today. I applied to fix and it works.
