### ISSUE TITLE
What are the changes between 1.8.1 and 2.0.0 ?

### ISSUE THREAD

**Issue by fungiboletus** [go-kivik/kivik#433]
Hi, thanks for your work and the new release 2.0.0. Are you following semantic versioning ? If so, could you have a short summary of the breaking changes in the release description ? Thank you very much.

**Comment by flimzy** [comment]
Thanks for asking. I should have included that in the original release announcement. I've now updated it with more complete release notes. Please see: http://kivik.io/v2-released
