### ISSUE TITLE
Website's link to godoc is broken

### ISSUE THREAD

**Issue by Warfields** [go-kivik/kivik#445]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
NA

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
NA

3. What did you do? (Include your code if possible)
NA

4. What did you expect to see?
on https://kivik.io/ clicking the go doc button should goto go docs, https://pkg.go.dev/github.com/go-kivik/kivik should be the new link

5. What did you see instead?
see attached image
![Screen Shot 2020-02-24 at 12 58 06 PM](https://user-images.githubusercontent.com/32973228/75186549-59b97200-5705-11ea-8817-61499c2bf305.png)

**Comment by flimzy** [comment]
Thank you for reporting this!  I'm not sure how to fix it yet, but it seems that links to pkg.go.dev are working, so for the time being, I'll update the link to point there.  I still want to fix it on godoc.org, of course, so I'll leave this open.
