### ISSUE TITLE
continuous feed not working unexpected EOF

### ISSUE THREAD

**Issue by pramodramdas** [go-kivik/kivik#467]
I am trying to watch changes on db. I am using pouchdb.
Below code waits for sometime and results in "unexpected EOF" error after one or two minutes. I am not sure if I am following it right. 
 
       client, err := kivik.New("couch", "http://localhost:3030/")
	if err != nil {
		panic(err)
	}
	ctx := context.Background()
	db := client.DB(ctx, "downloads")

	options := make(map[string]interface{})
	options["feed"] = "continuous"
	newChanges, err := db.Changes(ctx, options)
	for newChanges.Next() {
		data := newChanges.Changes()
		fmt.Print(data)
	}
	err = newChanges.Err()
	fmt.Println(err)
```

**Comment by flimzy** [comment]
You say you're using PouchDB, but your `New` call is clearly talking to CouchDB. Can you clarify that point?

The unexpected EOF is probably the result of the CouchDB server (assuming I can believe your code) is dropping the connection due to being idle.  You may need to add the [`heartbeat`](https://docs.couchdb.org/en/stable/api/database/changes.html#get--db-_changes) option, to keep the connection open:

```
options := make(map[string]interface{})
options["feed"] = "continuous"
options["heartbeat"] = 15000 // 15 seconds
```

**Comment by pramodramdas** [comment]
@flimzy , I am extremely sorry. I am using pouchdb and newChanges.Next() blocks for few minutes and then results in "unexpected EOF"

**Comment by flimzy** [comment]
> @flimzy , I am extremely sorry. I am using pouchdb and newChanges.Next() blocks for few minutes and then results in "unexpected EOF"

Can you clarify? Are you using PouchDB directly, or with Kivik?

In Kivik (and honestly, in standard PouchDB, too, or virtually any other method), it is expect for a call to `Next()` to block until the next value is ready, which could be immediate, or minutes, even hours or days, if the database does not receive many updates.

**Comment by pramodramdas** [comment]
@flimzy I am using pouchdb and code is same as I have mentioned. when I used 
kivik.New("pouch", "http://localhost:3030/")
or
kivik.New("pouchdb", "http://localhost:3030/")
I got this error
panic: kivik: unknown driver "pouchdb" (forgotten import?)

apart from continuous feed other feeds work fine with  kivik.New("couch", "http://localhost:3030/") even though I am using pouchDB as backend

Anyways here is my full code:
import(
	_ "github.com/go-kivik/couchdb/v4"
	"github.com/go-kivik/kivik"
)
client, err := kivik.New("pouchdb", "http://localhost:3030/")
	if err != nil {
		panic(err)
	}
	ctx := context.TODO()
	db := client.DB(ctx, "downloads")

	options := make(map[string]interface{})
	options["feed"] = "continuous"
	newChanges, err := db.Changes(ctx, options)
	fmt.Println(err)

	fmt.Println(newChanges.Changes())
	for newChanges.Next() {
		data := newChanges.Changes()
		fmt.Print(data)
	}
	err = newChanges.Err()
	fmt.Println(err)

**Comment by pramodramdas** [comment]
I am using pouchdb server. 
`pouchdb-server --port 3030 --in-memory`
and I am able to communicate to it through my nodejs http request

**Comment by flimzy** [comment]
> @flimzy I am using pouchdb and code is same as I have mentioned. when I used
> kivik.New("pouch", "http://localhost:3030/")
> or
> kivik.New("pouchdb", "http://localhost:3030/")
> I got this error
> panic: kivik: unknown driver "pouchdb" (forgotten import?)

The proper name is `pouch` [as documented](https://github.com/go-kivik/pouchdb).

This error means you have not loaded a driver by that name. If you're using PouchDB, you must load the driver, then use `"pouch"` as the driver name in your call to `New()`.


> apart from continuous feed other feeds work fine with kivik.New("couch", "http://localhost:3030/") even though I am using pouchDB as backend

No, this code uses CouchDB as the backend.  That's what "couch" means.

It is impossible for PouchDB to receive connections over HTTP.  Now maybe you can use the 'couch' driver with the PouchDB-Server, but that's not the same as PouchDB, which runs in the browser.

The code below is invalid, because you've loaded the CouchDB driver, then are trying to connect using the (misnamed) Pouch driver.

> Anyways here is my full code:
> import(
> _ "github.com/go-kivik/couchdb/v4"
> "github.com/go-kivik/kivik"
> )
> client, err := kivik.New("pouchdb", "http://localhost:3030/")
> if err != nil {
> panic(err)
> }
> ctx := context.TODO()
> db := client.DB(ctx, "downloads")
> 
> ```
> options := make(map[string]interface{})
> options["feed"] = "continuous"
> newChanges, err := db.Changes(ctx, options)
> fmt.Println(err)
> 
> fmt.Println(newChanges.Changes())
> for newChanges.Next() {
> 	data := newChanges.Changes()
> 	fmt.Print(data)
> }
> err = newChanges.Err()
> fmt.Println(err)
> ```

**Comment by flimzy** [comment]
> I am using pouchdb server.
> `pouchdb-server --port 3030 --in-memory`
> and I am able to communicate to it through my nodejs http request

Okay! That makes a big difference!

You still need to use the `couch` driver, then.

**Comment by pramodramdas** [comment]
@flimzy I tried adding `heartbeat`, but I am not able to see any response.

**Comment by flimzy** [comment]
> @flimzy I tried adding `heartbeat`, but I am not able to see any response.

Do you know that there are updates occurring to the database?

**Comment by pramodramdas** [comment]
Yes I modifing using http://localhost:3030/_utils/#/database/downloads/_all_docs.

**Comment by flimzy** [comment]
> Yes I modifing using http://localhost:3030/_utils/#/database/downloads/_all_docs.

`_all_docs` is a read-only operation. It does not perform any updates, so would not cause any changes on the changes feed.

**Comment by pramodramdas** [comment]
Then I wonder how nodejs code is working.

**Comment by flimzy** [comment]
I cannot comment on how or why your nodejs code works, not least of all because I cannot see it.

All I can offer is help in using Kivik, which I have provided above. Have you tried my suggestions? If so, what was the result?

**Comment by pramodramdas** [comment]
@flimzy I think I found the problem. Please refer my answer in [stackoverflow](https://stackoverflow.com/questions/61428031/keep-alive-request-for-change-continuous-feed/61495124#61495124 )  
I am assuming client := &http.Client{} sends DisableCompression : false by default, Hence received data was compressed(gzip) and resp.Body.Read was not able to read.
I checked by adding 
```
&http.Client{Transport: &http.Transport{
	DisableCompression: true,
}}
```
in `couchdb.go -> func (d *Couch) NewClient(dsn string)`, now I am able to see data

**Comment by flimzy** [comment]
@mcfilib I don't think whatever issue you're experiencing is related to this original issue for a couple reasons: 1. You're using AllDocs, and the OP is about Changes. 2. The logic has changed significantly in the last 3 years since this issue was first opened.

So yes, I would suggest opening a new issue with complete details.
