### ISSUE TITLE
Library panics when trying to get change sequence

### ISSUE THREAD

**Issue by stratg5** [go-kivik/kivik#469]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
Latest

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.x aims to support all versions of Go from 1.7. The master branch aims to support Go 1.8 and later.
1.12.17

3. What did you do? (Include your code if possible)
Use the .changes method. When there are no results, the lib panics when trying to get last sequence. This is not helpful however because if someone is setting up a poller to run periodically, they need the last sequence id or else they have to use "now", which is not very helpful bc they would miss changes since the last poll. The continuous changes also did not work, it cancelled my context after 1 minute instead of staying open.

4. What did you expect to see?
I should be able to access the last sequence id even without any results returned.

5. What did you see instead?
Panic

**Comment by flimzy** [comment]
Thank you for the bug report.  I'm unable to reproduce the panic you describe. Can you include the code you're using to produce the panic?

**Comment by stratg5** [comment]
Here is a sample piece of code -
changes, err := DB.Changes(context.Background(), map[string]interface{}{
		"include_docs": true,
		"since": "now",
	})
If no changes are found, I would still expect to get the last sequence id. But when I call changes.LastSeq(), I see a panic. This is because the iterator is nil (bc there are no changes). You should still return the last seq id even if no changes are found so that way I can reference it in future calls.

**Comment by flimzy** [comment]
Can you include the complete code that panics?  Are you calling `LastSeq()` directly on the next line? or are you attempting to iterate first? Or something else?

**Comment by stratg5** [comment]
Sure -

	changes, err := a.DB.Changes(context.Background(), map[string]interface{}{
		"include_docs": true,
		"since": "now",
	})
	if err != nil {
		//handle err
	}

//Panic happens on line below -
	changes.LastSeq()

**Comment by flimzy** [comment]
I have just released [v3.0.3](https://github.com/go-kivik/kivik/releases/tag/v3.0.3) to fix this problem.
Thanks again for the bug report.

**Comment by stratg5** [comment]
Awesome thanks so much!
