### ISSUE TITLE
Several Wiki / Documentation issues

### ISSUE THREAD

**Issue by iivvoo** [go-kivik/kivik#488]
I'm using Kivik  v4.0.0-20200429204048-e9102bc78740 and having some issues with the example code in the wiki.

Possibly the issues below are because of changes in version 4? Perhaps it's safer to use version 3 in stead though the project's README.md is unclear about which version is stable, v2 or v3

1. Error handling is really unclear / undocumented until you stumble upon the wiki main page. However, the code there is not entirely correct:

```
case kivik.StatusNotFound:
```

My version of kivik does not export a symbol StatusNotFound. It seems to work when using `http.StatusNotFound`

This example should probably be on the Usage-Examples page since testing for NotFound is quite essential

2. Fetching Document is incorrect.
https://github.com/go-kivik/kivik/wiki/Usage-Examples#fetching-a-document

`db.Get` does not return an error. In stead `row.Err` should be used. (but this might be a v3 vs v4 thingy?)

3. Couch view is incorrect.

The example code on https://github.com/go-kivik/kivik/wiki/Usage-Examples#create-or-update-a-view creates a view with key `view`. This should be `map` (and possibly `reduce`). This just confused me since I'm not too familiar with CouchDB either :)

**Comment by flimzy** [comment]
Thank you for the comments. The wiki is sadly outdated. I hope to move most of the wiki examples into the godoc, so that it's less likely to get out of sync in the future.

**Comment by flimzy** [comment]
I've just copied (and updated) most of the wiki contents into the godoc. But due to a [Bug in Go 1.14](https://github.com/golang/go/issues/38418) the examples are pretty unusable at the moment on pkg.go.dev. The fix should be included in 1.14.3, so I'll wait until that's released to close this issue and clean up the wiki.
