### ISSUE TITLE
Parsing 64 bit numbers

### ISSUE THREAD

**Issue by ccrotty** [go-kivik/kivik#498]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.
Version 3 
2. Which version of Go are you using? (Output of `go version`) -- Kivik 2.x supports Go 1.9 and later. Kivik 3.x requires Go 1.11 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.
1.14
3. What did you do? (Include your code if possible)
Created a document with 64 bit timestamp.  Added to CouchDB through kivik db PUT.  When I look at the timestamp field I see slightly different numbers between the Fauxton gui interface and a GET from the kivik db.

4. What did you expect to see?
The same 64 bit number.
5. What did you see instead?
Slightly different numbers (See how timestamp differs by 100)

In Fauxton...
{
 "id": "4be07798-9798-4f74-9b3f-6e16c5f80693",
 "key": 1591052173371913500,
 "value": 1,
 "doc": {
  "_id": "4be07798-9798-4f74-9b3f-6e16c5f80693",
  "_rev": "1-2da9a082c8568ecb6574a6c664ae0b2e",
  "name": "DummySessionName5",
  "filterA": 1,
  "filterB": "Filter5",
  "timestamp": 1591052173371913500
 }
}

From kivik.db...

{ID:4be07798-9798-4f74-9b3f-6e16c5f80693 Revision:1-2da9a082c8568ecb6574a6c664ae0b2e Name:DummySessionName5 FilterA:1 FilterB:Filter5 Timestamp:1591052173371913400}

Also to note: For a view based on doc.timestamp, I need to enter a key of ...3500 to match

**Comment by flimzy** [comment]
This is most likely a problem with CouchDB/SpiderMonkey, not Kivik.  Kivik uses the standard Go JSON marshaler/unmarshaler, which faithfully encodes and decodes large floating point numbers, but since SpiderMonkey, running in CouchDB, interprets these numbers as JavaScript numbers, they will be limited by JavaScript's floating point precision.

One possible solution would be to encode these values as strings, rather than as numbers, using the `,string` tag in your Go struct.  Example:

```golang
type Foo struct {
    LargeNumber int64 `json:"large_number,string"`
}
```

**Comment by ccrotty** [comment]
Yes, I did some further testing and I believe that is the case. Sorry for the false alarm.

FYI, I did seem some issues in decoding 64 bit integer numbers with json.Unmarshall as well (xlates to float64 internally).  Using the json.Decoder class and calling decoder.UseNumber() avoided this issue.
