### ISSUE TITLE
Is there any recommended usage documentation?

### ISSUE THREAD

**Issue by ccrotty** [go-kivik/kivik#499]
I'm curious if there were any best practices defined for the kivik library (specifically when used in golang).

I'm assuming that a kivik.Client object can be long lived, but what about the *DB object?  Should this be stored and reused, or should a new db object be grabbed when making a unique request.

Thanks,
Chris

**Comment by flimzy** [comment]
> I'm curious if there were any best practices defined for the kivik library (specifically when used in golang).

Kivik only works with Go, so I'm not really sure what distinction you're trying to make here... ?

> I'm assuming that a kivik.Client object can be long lived, but what about the *DB object? Should this be stored and reused, or should a new db object be grabbed when making a unique request.

A `DB` object can be long-lived, too. Whether that makes sense really depends on your application, and possibly on which driver you're using.  The `DB` struct is [pretty simple](https://github.com/go-kivik/kivik/blob/master/db.go#L16-L21), so it's very light-weight, so won't be a big memory burden:

```golang
type DB struct {
	client   *Client
	name     string
	driverDB driver.DB
	err      error
}
```

On the other hand, initializing a `DB` object is generally fairly cheap, as well. For the CouchDB driver, all it does is create a new instance. For PouchDB, or other drivers, there may be some validation that goes on, which could be a reason to to want to cache these objects.

All that said, do what makes sense in your application. If you need to use the same DB object frequently, cache it. If not, don't.  Premature optimization is the root of all evil...
