### ISSUE TITLE
Can not install kivik go package

### ISSUE THREAD

**Issue by ahmedsaifreza** [go-kivik/kivik#502]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? 
Tried on both v3 and v4

2. Which version of Go are you using? (Output of `go version`)
 --go version go1.14.4 windows/amd64

3. What did you do? (Include your code if possible)
Trying to install via following commands
go get github.com/go-kivik/kivik/v3 # Stable release
go get github.com/go-kivik/kivik/v4 # Development release

4. What did you expect to see?

5. What did you see instead?

PS C:\Users\ahmed> go get github.com/go-kivik/kivik/v3
package github.com/go-kivik/kivik/v3: cannot find package "github.com/go-kivik/kivik/v3" in any of:
        c:\go\src\github.com\go-kivik\kivik\v3 (from $GOROOT)
        C:\Users\ahmed\go\src\github.com\go-kivik\kivik\v3 (from $GOPATH)
PS C:\Users\ahmed> go get github.com/go-kivik/kivik/v4
package github.com/go-kivik/kivik/v4: cannot find package "github.com/go-kivik/kivik/v4" in any of:
        c:\go\src\github.com\go-kivik\kivik\v4 (from $GOROOT)
        C:\Users\ahmed\go\src\github.com\go-kivik\kivik\v4 (from $GOPATH)

**Comment by flimzy** [comment]
Can you paste the output of `go env`?

**Comment by ahmedsaifreza** [comment]
> Can you paste the output of `go env`?
`
PS C:\Users\ahmed> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ahmed\AppData\Local\go-build
set GOENV=C:\Users\ahmed\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ahmed\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ahmed\AppData\Local\Temp\go-build229683914=/tmp/go-build -gno-record-gcc-switches
`

**Comment by flimzy** [comment]
I'm sorry, I'm not sure what the problem is. And I don't have access to Go on Windows to test it myself. Whatever the problem, I see no evidence that it's a problem with Kivik. It's probably something about the way Go is configured on your system.

If you find additional information that suggests Kivik is specifically to blame, please re-open the issue.
