### ISSUE TITLE
running into "too many open sockets"

### ISSUE THREAD

**Issue by wasperen** [go-kivik/kivik#517]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using?
v3

2. Which version of Go are you using? 
go version go1.15.4 linux/amd64

3. What did you do? (Include your code if possible)
I need to run hundreds to thousands of queries.

Created a method that runs the query and sends keys and values to a channel:
```
func (h *ExplorationDBHandler) getSubjectRows(explorationID, originStart, originEnd string, inclusiveEnd bool) (chan *subjectKeyValue, error) {
	ctx, _ := context.WithTimeout(context.Background(), h.CouchdbHandler.ClientTimeout)
	var (
		rows *kivik.Rows
		err  error
	)
	for rety := 4; rety >= 0; rety-- {
		rows, err = h.CouchdbHandler.Database.Query(ctx, "_design/cynthia-explorations", "_view/by_exploration-subject-tree", kivik.Options{
			"startkey":      [...]string{explorationID, originStart, "", "A", ""},
			"endkey":        [...]string{explorationID, originEnd, kivik.EndKeySuffix, kivik.EndKeySuffix, kivik.EndKeySuffix},
			"reduce":        true,
			"group_level":   5,
			"include_docs":  false,
			"inclusive_end": inclusiveEnd,
		})
		if err != nil {
			sugar.Errorf("failed to read origin_subjects / subject pairs for exploration id %s; error %s", explorationID, err.Error())
		}
	}
	keyValueChan := make(chan *subjectKeyValue, 0)

	go func() {
		defer func() {
			close(keyValueChan)
			rows.Close()
		}()

		for rows.Next() {
			key := &keyType{}
			if err := rows.ScanKey(&key); err != nil {
				sugar.Errorf("failed to get key for origin_subjects / subject pairs for exploration id %s; error %s", explorationID, err.Error())
				return
			}
			var count uint16
			if err := rows.ScanValue(&count); err != nil {
				sugar.Errorf("failed to get value for origin_subjects / subject pairs for exploration id %s; error %s", explorationID, err.Error())
				return
			}
			keyValueChan <- &subjectKeyValue{
				key:   key,
				value: count,
			}
		}
	}()

	return keyValueChan, nil
}
```

Here the `ExplorationDBHandler` is created as follows:
```

func (h *ExplorationDBHandler) init(address, database string, timeoutSeconds uint16) error {
	var err error

	h.client, err = kivik.New("couch", address)
	if err != nil {
		return err
	}

	h.DatabaseName = database
	h.ClientTimeout = time.Second * time.Duration(timeoutSeconds)

	ctx, _ := context.WithTimeout(context.Background(), h.ClientTimeout)
	h.Database = h.client.DB(ctx, h.DatabaseName)

	return nil
}
```

I then hit this from many different go functions, going through thousands of values, in essence running many many queries in parallel. I then run into:
```
error of type *chttp.curlError: Get "http://127.0.0.1:5984/cynthia_explorations/_design/cynthia-explorations/_view/by_exploration-subject-tree?endkey=%5B%2229797cc2-ccb3-4e03-ba26-a541e2e5dbce%22%2C%22cancer+program%22%2C%22%EF%BF%B0%22%2C%22%EF%BF%B0%22%2C%22%EF%BF%B0%22%5D&group_level=5&include_docs=false&inclusive_end=true&reduce=true&startkey=%5B%2229797cc2-ccb3-4e03-ba26-a541e2e5dbce%22%2C%22cancer+program%22%2C%22%22%2C%22A%22%2C%22%22%5D": dial tcp 127.0.0.1:5984: socket: too many open files
```
I am sure I should be closing some resource -- just not sure what.

**Comment by flimzy** [comment]
It's not obvious to me what's causing too many open files.  I do see a few resource leaks in your code, though, that probably aren't related to this specific problem.

1. You're discarding the context cancelation functions. You should never do this.  i.e.:

```golang
	ctx, _ := context.WithTimeout(context.Background(), h.ClientTimeout)
```

should be:

```golang
	ctx, cancel := context.WithTimeout(context.Background(), h.ClientTimeout)
	defer cancel()
```

2. You're never calling `rows.Err()`, which means that any network read errors will go undetected.

Aside from those two issues, can you give me a bit more context about how you're using the code?  Are you calling the query multiple times concurrently?  Does the error happen quickly, or after a long time (minutes, hours, days?) of operation?

Ideal would be to come up with a minimal reproduction case that I can reproduce on demand, to allow for proper debuggin and a fix.

Thanks.

**Comment by wasperen** [comment]
Many thanks! Indeed, I am hitting this query from a large number of go functions in parallel. Just calling the `cancel` function when done fixes this! I'll also check the `rows.Err()` function to check any networking errors.

**Comment by flimzy** [comment]
:+1: 

I'm glad it was that easy to fix!  :tada:
