### ISSUE TITLE
Receiving 200 OK while using Query() but ending up with 0 rows

### ISSUE THREAD

**Issue by Bekreth** [go-kivik/kivik#526]
1. Which version of Kivik are you using? Please state a version number, or `master`.

github.com/go-kivik/couchdb/v3 v3.2.5
github.com/go-kivik/kivik/v3 v3.2.3

2. Which version of Go are you using? (Output of `go version`) -- Kivik 2.x supports Go 1.9 and later. Kivik 3.x requires Go 1.11 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.

go version go1.13.5 linux/amd64

3. What did you do? (Include your code if possible)
I'm attempting to query a local instance for its view.
Here's a stripped down version of the Go code
```
client, _ := kivik.New(databaseDriver, "localhost:5984")
authentication := driver.BasicAuth(config.Username, config.Password)
client.Authenticate(context.Background(), authentication)

db := client.DB(context.Background(), "records")
rows, err := db.Query(context.Background(), "searchDocs", "created_date")
if rows.TotalRows() == 0 {
  panic(err)
}
```
And the CouchDB design doc
```
{
  "_id": "_design/searchDocs",
  "_rev": "1-0cac9b8cfb6fea70187375d92aca6ea1",
  "views": {
    "created_date": {
      "map": "function (doc) {\n  if (doc.created_date) emit(doc.created_date.seconds, doc);\n  else emit(null, doc);\n}"
    }
}
```

4. What did you expect to see?

I was expecting to see the data associated with this view.  I've been able to query my CouchDB instance directly like so (http://localhost:5984/records/_design/searchDocs/_view/created_date) using curl and I've used this DB connection to write, delete, and read specific records.

5. What did you see instead?

Diving into it a little bit, the driver is connecting the the CouchDB instance and receiving a 200 OK response, but the `rows` object is always empty.  The example of using the `Query()` function I found here specifies start and end keys as well as providing the `_design` and `_view` path parameters as part of the list.  I've mix and matched a handful of these combinations without success.  

https://github.com/go-kivik/kivik/blob/master/db_example_test.go

At the moment I assume this is user error;  could you provide some details about how to do a read query against a view?

**Comment by flimzy** [comment]
`TotalRows` cannot be read until all rows have been iterated. This is because the `total_rows` key is not guaranteed to be included before the first row (and in practice, in current version of CouchDB, it's always after).  So calling `rows.TotalRows()` will always return `0` before iteration has completed.  This is mentioned [in the documentation](https://pkg.go.dev/github.com/go-kivik/kivik/v3#Rows.TotalRows):

> TotalRows returns the total number of rows in the view which would have been returned if no limiting were used. This value is only guaranteed to be set after all result rows have been enumerated through by Next, and thus should only be read after processing all rows in a result set. Calling Close before enumerating will render this value unreliable.

This comes up pretty frequently, though, so maybe I need to find some way to make it more obvious.  Without breaking the existing API, I could make it return `-1` before it's been set, for example... not sure if that would be an improvement.... :thinking:

**Comment by Bekreth** [comment]
Wow, that was phenomenally silly of me.... I really did spend quite a while looking for the cause of this issue and somehow avoided reading the Go-Docs for the function itself.  Thank you for the quick turn around!
