### ISSUE TITLE
Small but confusing documentation issue after API change

### ISSUE THREAD

**Issue by iivvoo** [go-kivik/kivik#527]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.

v4.0.0-20201202093909-da42f0daa1b2

2. Which version of Go are you using? (Output of `go version`) -- Kivik 2.x supports Go 1.9 and later. Kivik 3.x requires Go 1.11 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.

1.14.2

3. What did you do? (Include your code if possible)

Our kivik/v4 got recently updated. After that our BulkDocs calls started failing with the error `Bad Request: Document must be a JSON object`

Turns out `BulkDocs` no longer accepts a []interface{} holding byte-slices, even though the documentation suggests it still does

> As with Put, each individual document may be a JSON-marshable object, or a
> raw JSON string in a []byte, json.RawMessage, or io.Reader.

In stead, it base64-encodes the body

```
{"docs":["eyJhIjoiMTIzIn0="]}
```
Wrapping the []byte slice in a json.RawMessage() fixes things, but it wasn't obvious.

4. What did you expect to see?

The documentation not to mention []byte anymore.

5. What did you see instead?

It did still mention it :)

**Comment by flimzy** [comment]
Thanks for reporting this oversight!  Should be fixed now.
