### ISSUE TITLE
AllDocs iterating rows ScanDoc panics on doc == nil

### ISSUE THREAD

**Issue by NickBelhomme** [go-kivik/kivik#529]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.
	github.com/go-kivik/couchdb v2.0.0+incompatible
	github.com/go-kivik/kivik v2.0.0+incompatible

2. Which version of Go are you using? (Output of `go version`) -- Kivik 2.x supports Go 1.9 and later. Kivik 3.x requires Go 1.11 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.
1.15.7

3. What did you do? (Include your code if possible)

```
func (r Repository) Find(id string) partnerdomain.Partner {
	var partnerDocument PartnerDocument
	err := db(r).Get(context.TODO(), id).ScanDoc(&partnerDocument)
	if err != nil {
		panic(err)
	}

	partner := partnerdomain.PartnerImpl{}

	hydrate(&partner, partnerDocument)
	return &partner
}

func (r Repository) All() []partnerdomain.Partner {
	rows, err := db(r).AllDocs(context.TODO())
	if err != nil {
		panic(err)
	}

	var result []partnerdomain.Partner
	for rows.Next() {
		var partnerDocument PartnerDocument
		if err := rows.ScanDoc(&partnerDocument); err != nil {
			panic(err)
		}
		p := partnerdomain.PartnerImpl{}

		hydrate(&p, partnerDocument)
		result = append(result, &p)
	}
	if rows.Err() != nil {
		panic(rows.Err())
	}

	return result
}
```

4. What did you expect to see?
a Row unmarshaled into partnerDocument when doing ```rows.ScanDoc(&partnerDocument);```

5. What did you see instead?

It seems to say the documents are nil? While Find(123456) actually returns a document...
When I do All() I get a panic "kivik: doc is nil; does the query include docs?"

The panic is originating from here:
```
func (r *Rows) ScanDoc(dest interface{}) error {
	runlock, err := r.rlock()
	if err != nil {
		return err
	}
	defer runlock()
	if err := r.curVal.(*driver.Row).Error; err != nil {
		return err
	}
	doc := r.curVal.(*driver.Row).Doc
	if doc == nil {
		return &Error{HTTPStatus: http.StatusBadRequest, Message: "kivik: doc is nil; does the query include docs?"}
	}
	return scan(dest, doc)
}
```

**Comment by flimzy** [comment]
You need to instruct your query to include docs:

```golang
rows, err := db(r).AllDocs(context.TODO(), kivik.Options{"include_docs": true})
```

**Comment by NickBelhomme** [comment]
Thanks. Works.
