### ISSUE TITLE
Case insensitive regex queries

### ISSUE THREAD

**Issue by muety** [go-kivik/kivik#538]
I'm using Kivik to access a database running on the latest version of [pouchdb-server](https://github.com/pouchdb/pouchdb-server). I'd like to be able to run case-insensitive regex queries. Consider this example:

```go
rows, err := s.db.Find(context.TODO(), map[string]interface{}{
    "selector": map[string]interface{}{
        "title": map[string]interface{}{
	     "$regex": "Bar",
        },
    },
})
```

Having a document with `{ "title": "Foo Bar Baz" }`, the above query will succeed and return the document. However, I'd still like to find it if my regex was `bar` (lower case). 

Using `(?i)bar` as a regex yield the following error:

```
Bad Request: Invalid regular expression: /(?i)bar/: Invalid group
```

**Edit:** I assume this might instead be an issue with PouchDB itself, rather than with Kivik?

**Comment by flimzy** [comment]
This does look like something from PouchDB-server.  Kivik should just pass that string unprocessed, to the server directly.  So any error that comes from parsing that string must come from the server.

**Comment by muety** [comment]
Thanks for the quick reply! I filed an issue upstream (https://github.com/pouchdb/pouchdb-server/issues/445). Let's see what happens.
