### ISSUE TITLE
kivik fails uploading attachments to cb-sg 

### ISSUE THREAD

**Issue by ghitchens** [go-kivik/kivik#541]
I realize you likely aren't supporting couchbase-sync-gateway (cb-sg) as a server, but if you have any ideas as to why this might be happening, I'd sure appreciate it..   I have experience with PouchDB, CouchDB, and most recently have been using Couchbase with the Sync Gateway via the legacy REST (CouchDB compatible) API.   I'm trying to use Kivik to interface with cb-sg and it works flawlessly for the cases I've tried, except this one..

1. Which version of Kivik are you using? Please state a version number, or `master`.

I am using Kivik v3.2.3

2. Which version of Go are you using? (Output of `go version`)

```sh
garth@fernie ~ % go version
go version go1.16.6 darwin/arm64
```

3. What did you do? (Include your code if possible

Tried to post an attachment...

```go
func TestPutWithAttachment(t *testing.T) {

	type Doc struct {
		Attachments kivik.Attachments `json:"_attachments"`
	}

	doc := Doc{
		Attachments: kivik.Attachments{
			"foo.txt": &kivik.Attachment{
				Filename:    "foo.txt",
				ContentType: "text/plain",
				Content:     ioutil.NopCloser(strings.NewReader("this is an attachment text file")),
			},
		},
	}

	if rev, err := sync.DB.Put(context.TODO(), "test_doc_2", doc); err != nil {
		t.Errorf("put %v", err)
	} else {
		t.Logf("put ok, new rev %s", rev)
	}
}
```

4. What did you expect to see?

Expected to see success -- attachment created

5. What did you see instead?

```
-- FAIL: TestPutWithAttachment (0.04s)
    sync_test.go:30: put Bad Request: MIME part #2 doesn't match any attachment
FAIL
exit status 1
```

If I change the json tag to "attachments" rather than "_attachments", it posts the encoded data as expected (since it isn't handled by couch base sync gateway's attachment handling code).     I know this error is coming from couchbase sync gateway and not from kivik, but I am wondering if it looks like I am creating attachments as expected and if you can think of reasons it would have trouble putting this new document with attachments?   

If I create the same document using pouchDB in javascript connected to the sync gateway, it works.  I am assuming there is some incompatibility with multipart-mime uploads from kivik to couchbase, but honestly that's way above my expertise.

I thought I might try PutAttachment but that bumps the revision so I can't update the item and attachments in a single revision.    I also don't know if that would work either.

Any ideas as to if I"m doing something obviously wrong would be appreciated..

The relevant part of cb-sg is in multipart.go. around line 255 (if interested, see https://github.com/couchbase/sync_gateway)
```go

		digest := db.Sha1DigestKey(data)
		name, meta := findFollowingAttachment(digest)
		if meta == nil {
			name, meta = findFollowingAttachment(md5DigestKey(data))
			if meta == nil {
				return nil, base.HTTPErrorf(http.StatusBadRequest,
					"MIME part #%d doesn't match any attachment", i+2)
			}
		}
```

**Comment by flimzy** [comment]
I'm not familiar with cb-sg, so have not tested with it.  It looks like it's not interpreting the multipart upload the same way CouchDB does, which may be a bug in Kivik.  As a test, and possible work-around, can you disable the multipart put as described [here](https://pkg.go.dev/github.com/go-kivik/couchdb/v3#hdr-Multipart_PUT), and let me know the results? i.e.:

```golang
	if rev, err := sync.DB.Put(context.TODO(), "test_doc_2", doc, kivik.Options(couchdb.NoMultipartPut: true); err != nil {
```

**Comment by ghitchens** [comment]
Yes, that did indeed work.   Thanks, I will use that as a workaround for now.    I agree this could be a bug in cb-sg, although it works well with PouchDB.   Couchbase hasn't kept 100% CouchDB API compatibility as a priority in the Sync Gateway, and they've moved onto a V2 API which is incompatible entirely, but the CouchDB API still works, and they have continued to fixing issues raised against the CouchDB API.

Overall I will use this workaround as a temporary solution.  For my application, which uses PouchDB on the web client, I'm increasingly finding edge cases and compromises in trying to attachments (even small ones) in the documents.   I've been keeping thumbnails of files, documents, and images in the _attachments and the main image or document in S3, but I'm increasingly thinking I should move all attachments (even thumbnails) to external replicated storage of some kind (maybe lighter weight than S3 for the smaller files) and just keep the metadata and a UUID references in the document. 

Thanks again for your great work on Kivik.  I really like it.  I"m new to Go (having worked with Elixir for quite some time) and Kivik is one of the main reasons I'm staying (along with gocb).  I keep running across your posts -- gopherJS looks pretty interesting, as does testy.   A vibrant community is one of the things I loved about Elixir and glad to see Go has people like you involved.   Since I'm building an sevice that will need some significant scaling and devops on a tiny budget, I'm heading off to read your blog on those topics.

Back to the bug.. .I am not sure I am qualified to determine if the bug is cb-sg or kivik. i  Multipart encoding has never been something I had an understanding of.   If you want to just close this as "kivik doesn't  support cb-sg" I'd understand.  If there is a further test you'd like me to try I'm happy to do so.    I will say the combo of kivik and cb-sg has been pretty nice.

**Comment by flimzy** [comment]
I'm glad to hear that worked!  Before closing this issue, I'd like to convirm whether cb-sg tries to support multipart PUTs like this. If it does, at least a reasonable effort should be made by Kivik to support it.

So I'll leave this open for now.  I'm not sure when I'll have time to investigate that, but I'll try to get to it before too long.

Thanks for reporting!

**Comment by flimzy** [comment]
I've consulsted the sync gateway docs: https://blog.couchbase.com/store-sync-binary-data-attachments-blobs-couchbase-mobile/

Although the docs are not explicit about _not_ supporting multipart uploads, they don't mention that they are supported either, so I'm going to assume they simply are not supported.

So I'm going to go ahead and close this issue.

If this proves to be a bigger problem for more people, it may be something to consider auto-detecting the presence of sync gateway to disable multipart attachments automatically, but I'm not sure of a reliable way to do that, so I'll wait to see if it becomes more of an issue before exploring that possibility.
