### ISSUE TITLE
Not getting the documents from view that match key while using Query function

### ISSUE THREAD

**Issue by PreethiVuchuru27916** [go-kivik/kivik#571]
1. Which version of Kivik are you using? Please state a version number, or `master`.
"github.com/go-kivik/kivik/v3", "github.com/go-kivik/couchdb/v3"

2. Which version of Go are you using? (Output of `go version`) -- Kivik 3.x supports Go 1.9 and later. Kivik 4.x requires Go 1.13 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.
go version go1.18.3 darwin/amd64

3. What did you do? (Include your code if possible)
I'm trying to get the documents from a view which has the specific key that is passed through options. 
rows, _ := db.Query(context.TODO(), "_design/OrganizationInfo", "GetMultipleDocsByBAT", kivik.Options{
		"key": "Company",
})
for rows.Next() {
    var doc interface{}
    if err := rows.ScanDoc(&doc); err != nil {
        panic(err)
    }
    fmt.Println(doc)
}
if rows.Err() != nil {
    panic(rows.Err())
}

4. What did you expect to see?
Documents from the view GetMultipleDocsByBAT that has key Company

5. What did you see instead?
panic: kivik: doc is nil; does the query include docs?

goroutine 1 [running]:
main.main()
        /Users/PreethiVuchuru/Projects/RA/ri-prototype/mini/main.go:83 +0x219
exit status 2

**Comment by flimzy** [comment]
Yes, it's becuase this is how CouchDB works.  If you don't pass `include_docs = true`, the documents are not included in the response.

This is documented [here](https://docs.couchdb.org/en/stable/api/ddoc/views.html#api-ddoc-view):

> - **include_docs** *(boolean)* – Include the associated document with each row. Default is false.
