### ISSUE TITLE
Strange behaviour while calling ScanDoc on ResultSet

### ISSUE THREAD

**Issue by robsztal** [go-kivik/kivik#576]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.
- v4.0.0
2. Which version of Go are you using? (Output of `go version`) -- Kivik 3.x supports Go 1.9 and later. Kivik 4.x requires Go 1.13 or later, with module support. The Kivik 4/master aims to support Go 1.11 and later, with module support.

- 1.19.3

4. What did you do? (Include your code if possible)

I want to get one specific document with specific id prefix so I am using Find with query selector

```go
doc := db.Find(ctx, query)
res := model.ExampleModel{}
err = doc.ScanDoc(&res)
```

5. What did you expect to see?

two cases:
- first when there is no document I want empty res or error from ScanDoc?
- second where there is a document I want filled res

7. What did you see instead?
- first example: ScanDoc stays in infinite loop
- second example: works fine 

When I am using :
```go
doc := db.Find(ctx, query)
res := model.ExampleModel{}
for doc.Next() {
		err = doc.ScanDoc(&res)
	}
```

it works like intended but despite that why code is entering infinite loop instead of error or something?

**Comment by robsztal** [comment]
@flimzy Ok great! Thanks for reply.

**Comment by flimzy** [comment]
I believe I have now reproduced this, and have a good idea the cause. I hope to have a fix soon.
