### ISSUE TITLE
feat: Update wikipedia with multi-query example

### ISSUE THREAD

**Issue by mtz29** [go-kivik/kivik#612]
At the moment Wiki examples lack multi-query code snippet. I spent 3h to figure out why I was getting my data repeated.

Is this correct approach?

```go

...
cows := make([]Cow, 0, 100)
for rows.Next() {

	if rows.EOQ() {
		continue
	}

	var cow Animal
	if err := rows.ScanDoc(&cow); err != nil {
		continue
	}

       cows = append(cows, cow)

...
```

**Comment by flimzy** [comment]
Have you seen this? https://pkg.go.dev/github.com/go-kivik/kivik/v3#example-Rows-EOQ

**Comment by mtz29** [comment]
> Have you seen this? https://pkg.go.dev/github.com/go-kivik/kivik/v3#example-Rows-EOQ

No I have not. Reverse engineering kivik/couchdb driver code helped me to get to the point.

Please add the multi-query section to github Wiki (https://github.com/go-kivik/kivik/wiki/Usage-Examples).

**Comment by flimzy** [comment]
What details do you feel is left uncovered by the documentation example?

**Comment by mtz29** [comment]
> What details do you feel is left uncovered by the documentation example?

# Query a view with multiple keys
```go
rows, err := db.Query(context.TODO(), "_design/foo", "_view/bar", kivik.Options{
 "queries": []kivik.Options{
      kivik.Options {
          "startkey": []string{"foo", "bar"},
          "endkey":   []string{"foo", "bar" + kivik.EndKeySuffix},
          "include_docs": true,
      },
      kivik.Options {
          "startkey": []string{"baz", "bar"},
          "endkey":   []string{"baz", "bar" + kivik.EndKeySuffix},
          "include_docs": true,
      },
  }
})

if err != nil {
	panic(err)
}

cows := make([]Cow, 0, 100)
for rows.Next() {

	if rows.EOQ() {
		continue
	}

	var cow Animal
	if err := rows.ScanDoc(&cow); err != nil {
		continue
	}

       cows = append(cows, cow)

```

**Comment by flimzy** [comment]
I'm confused. The original question appears to be about how to perform multiple queries, yes?  That is already documented in the link I provided.  But now you're talking about querying with multiple keys?

**Comment by mtz29** [comment]
> I'm confused. The original question appears to be about how to perform multiple queries, yes? That is already documented in the link I provided. But now you're talking about querying with multiple keys?

This is just a proposition, maybe not very well named, but it is still about multi-query. The link you provided is ok, yet as stated before, that should've been placed in Wiki too.
