### ISSUE TITLE
couchdb: "+" sign in database name is not being escaped

### ISSUE THREAD

**Issue by tan-tony** [go-kivik/kivik#661]
db object currently is initialized using url.PathEscape()
`	return &db{
		client: c,
		dbName: url.PathEscape(dbName),
	}, nil
}`
In the case where the database has a "+" sign, for example "name+123" should get escaped to "name%2B123", however, url.PathEscape() is not doing so. 
Hence suggesting to either explicitly handle the case, or use url.QueryEscape().

**Comment by flimzy** [comment]
I'm looking closely at this now, to get any last minute breaking changes in before I roll v4, and I'm not actually sure this is a valid bug report.

`+` is a valid character in the path portion of a URL. It's only in a query parameter that it is converted to a space, and thus needs to be escaped (and this is what CouchDB was handling incorrectly).

If you're still having an issue here, would you be willing to provide a bit more information about the exact query you're using, and the ill behavior it's producing?

Thanks.

**Comment by flimzy** [comment]
I'm going to close this issue, but would be happy to re-open it if we can get some additional info with a reproduction case.
