### ISSUE TITLE
AllDocs fails with unexpected EOF

### ISSUE THREAD

**Issue by philipcunningham** [go-kivik/kivik#843]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.

```
github.com/go-kivik/kivik/v4 v4.0.1
```

3. Which version of Go are you using? (Output of `go version`) -- Kivik 3.x supports Go 1.13 and later. Kivik 4.x requires Go 1.17 or later.

```
go version go1.20.1 darwin/arm64
```

5. What did you do? (Include your code if possible)

Called `AllDocs` on a private replica of the NPM CouchDB registry. Here's some example code of this running against a public replica:

```go
package main

import (
	"context"
	"fmt"

	kivik "github.com/go-kivik/kivik/v4"
	_ "github.com/go-kivik/kivik/v4/couchdb"
)

type npmDoc struct {
	Name string `json:"name"`
}

func main() {
	client, err := kivik.New("couch", "https://skimdb.npmjs.com") // public replica
	if err != nil {
		panic(err)
	}

	db := client.DB("registry")

	results := db.AllDocs(context.TODO(),
		kivik.Param("descending", false),
		kivik.Param("include_docs", true))

	for results.Next() {
		var doc npmDoc

		err := results.ScanDoc(&doc)
		if err != nil {
			panic(err)
		}

		fmt.Println(doc.Name)
	}

	if err := results.Err(); err != nil {
		panic(err)
	}
}
```

Please note that the public NPM registry has some built-in rate-limiting and so far I've only been able to reproduce against my private replica:

<details>

```go
package main

import (
	"context"
	"fmt"
	"os"

	kivik "github.com/go-kivik/kivik/v4"
	"github.com/go-kivik/kivik/v4/couchdb"
)

type npmDoc struct {
	Name string `json:"name"`
}

func main() {
	client, err := kivik.New("couch", os.Getenv("NPM_SERVER"), couchdb.BasicAuth(os.Getenv("NPM_USER"), os.Getenv("NPM_PASSWORD")))
	if err != nil {
		panic(err)
	}

	db := client.DB(os.Getenv("NPM_DB"))

	results := db.AllDocs(context.TODO(),
		kivik.Param("descending", false),
		kivik.Param("include_docs", true))

	for results.Next() {
		var doc npmDoc

		err := results.ScanDoc(&doc)
		if err != nil {
			panic(err)
		}

		fmt.Println(doc.Name)
	}

	if err := results.Err(); err != nil {
		panic(err)
	}
}
```

The output looks something like this and the panic isn't always preceded by the same package name:

```
@8base/file-server-sdk
@8base/forms
@8base/functions-types
@8base/generators
@8base/graphiql
@8base/permissions-provider
panic: unexpected EOF
```

</details>

7. What did you expect to see?

I expected this code to eventually enumerate all the packages in my private replica.

9. What did you see instead?

```
unexpected EOF
```

**Comment by flimzy** [comment]
Thanks for the report. How did you set up your private replica? Is this process documented somewhere?

**Comment by flimzy** [comment]
If we can devise a reproduction case that won't require weeks, I'm happy to further investigate.  If you're convinced it's a CouchDB issue, though, I'm happy to have the issue closed as well.
