### ISSUE TITLE
Question: Is v4 still considered experimental and v3 still the stable version?

### ISSUE THREAD

**Issue by ccrotty** [go-kivik/kivik#900]
## Bug Report Checklist (remove this template if submitting a feature request)

1. Which version of Kivik are you using? Please state a version number, or `master`.

2. Which version of Go are you using? (Output of `go version`) -- Kivik 3.x supports Go 1.13 and later. Kivik 4.x requires Go 1.17 or later.

3. What did you do? (Include your code if possible)

4. What did you expect to see?

5. What did you see instead?

**Comment by flimzy** [comment]
v4 is now stable. Did you see it listed as experimental somewhere? I may have failed to update that somewhere.

**Comment by ccrotty** [comment]
Under the **Versions** heading in the readme.md.  It says we are looking at the development branch and has a link to the stable version (v3).

**Comment by flimzy** [comment]
Thanks. I'll get that fixed.
